// Generated by CoffeeScript 2.4.1 I Hate CoffeeScript 2019 And I Was Far Too Peeved To Fix This Stupid Code
(function() {
    var TwitterModule, http, imgPattern, msgPattern, request;

    http = require('https');

    request = require('request-promise');

    imgPattern = /<meta\s+property="og:image"\s+content="(.+)">/g;

    msgPattern = /https:\/\/twitter.com\/[a-zA-Z0-9_]+\/status\/[0-9]+/g;

    TwitterModule = class TwitterModule extends BotModule {
        ready() {
            return this.registerEvent('discord.message', (message) => {
                /*
                req = http.get url, (res) ->
                    status = res.statusCode
                    message.channel.send status
                    if status == 200
                        val = ''
                        res.on 'data', (chunk) ->
                val += chunk.toString()
                        res.on 'end', () ->
                match = imgPattern.exec(val)
                while(match != null)
                    message.channel.send match[1]
                    match = imgPattern.exec(val)
                */
                var check, match, url;
                if (message.content[0] === '!') {
                    return;
                }

                check = {};
                do {
                    match = msgPattern.exec(message.content);
                    if(!match)
                        continue;

                    url = match[0];
                    if(url in check)
                        continue;
                    check[url] = true;

                    request(url)
                        .then(function(data) {
                            var imatch;
                            imatch = imgPattern.exec(data);
                            do {
                                imatch = imgPattern.exec(data);
                                if(!imatch)
                                    continue;

                                message.channel.send(imatch[1]);
                            } while(imatch)
                        })
                        .catch(function(err) {

                        });
                } while (match)
            });
        }

    };

    module.exports = TwitterModule;

}).call(this);
